<?php

namespace ContainerAuBIRI1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9T6y2yService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9_t6y2y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9_t6y2y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'car' => ['privates', '.errored..service_locator.9_t6y2y.App\\Entity\\Car', NULL, 'Cannot autowire service ".service_locator.9_t6y2y": it references class "App\\Entity\\Car" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'car' => 'App\\Entity\\Car',
            'entityManager' => '?',
            'slugger' => '?',
        ]);
    }
}
