<?php

namespace ContainerAuBIRI1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9_t6y2y.App\Entity\Car' shared service.
     *
     * @return \App\Entity\Car
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.9_t6y2y": it references class "App\\Entity\\Car" but no such service exists.');
    }
}
