<?php

namespace ContainerJoxHilX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kln4w22Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Kln4w22' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Kln4w22'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'billingRepository' => ['privates', 'App\\Repository\\BillingRepository', 'getBillingRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'billingRepository' => 'App\\Repository\\BillingRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
