<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAuBIRI1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAuBIRI1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAuBIRI1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAuBIRI1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAuBIRI1\App_KernelDevDebugContainer([
    'container.build_hash' => 'AuBIRI1',
    'container.build_id' => '0376d147',
    'container.build_time' => 1636379316,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAuBIRI1');
